### ISSUE TITLE
Kein Abruf der Kontoliste möglich

### ISSUE THREAD

**Issue by zenminimalist** [gharlan/moneymoney-shoop#1]
Bei mir erscheint die Meldung: 

>Konnte die Kontenliste nicht abfragen.

Im Protokoll steht: 
       
  Shoop.lua: expected string for 'account.accountNumber'
          Konnte die Kontenliste nicht abfragen.

Obwohl Benutzername und Passwort richtig sind, da ich mich einwandfrei einloggen kann. Nutze derzeit MoneyMoney Version 2.3.3

**Comment by gharlan** [comment]
Hmm, kann ich bei mir nicht nachvollziehen.
Logg dich bitte mal bei shoop ein und öffne diese Seite:
https://www.shoop.de/my/settings.php

Steht da etwas bei Benutzer-Daten -> Benutzername?

**Comment by zenminimalist** [comment]
Den Benutzername habe ich auch schon versucht. Leider dasselbe Problem : (

**Comment by zenminimalist** [comment]
Hab's heute und gestern nochmal probiert und sogar einmal ausgesperrt, da der Benutzername oder Passwort falsch sind. Mit den gleichen Daten kann ich mich ohne Probleme einloggen. Kann ich dir irgendwelche Infos geben damit man diesem Problem auf die Schliche kommt? Nutzt du ebenso die Version 2.3.3?

**Comment by zenminimalist** [comment]
So, ich habe nun endlich das Problem gefunden. Es waren anscheinend die Sonderzeichen in meinem Password die zur Ablehnung geführt haben. Alles andere NICHT funktioniert. Nun habe ich ein viel längeres Password OHNE Sonderzeichen gewählt.
