### ISSUE TITLE
Login nicht möglich, Konto-Sperrung

### ISSUE THREAD

**Issue by christophbach** [gharlan/moneymoney-shoop#2]
Hallo Gregor,

es ist nicht möglich, sich weiterhin mit der Extension anzumelden. Die Verbindung wird nicht zugelassen. Gleichzeitig gehen bei Shoop offenbar ein paar Alarmglocken an und das Konto wird gesperrt. Das Repo hat bereits ein paar Tage auf dem Buckel. Da es aber noch bei MoneyMoney in der Erweiterungsliste auftaucht, halte ich eine Rückmeldung diesbezüglich für sinnvoll.

**Comment by gharlan** [comment]
Hmm, kann ich hier bisher nicht feststellen, der Abruf funktioniert bei mir noch.

**Comment by rawwry** [comment]
Moin Gregor. 

Ich habe das gleiche Problem wie Christoph. Seit einigen Tagen mosert Moneymoney rum dass die Informationen nicht abgerufen werden können. 

Fehlermeldung "Konnte die Kontenliste nicht abfragen."

Ich hab Dir mal nen Screenshot vom Protokoll dazu 

gepackt. Vielleicht hilft das ja bei irgendwas? :)


![mm](https://user-images.githubusercontent.com/30184072/47598124-db758000-d997-11e8-808b-7dbbb0030b3a.jpg)

**Comment by ruaq** [comment]
Same here!

Wollte das Konto neu anlegen und werde rausgeworfen. Scheinbar macht beta.shoop.de Probleme. Aber danach ob er die beta URL ansteuern soll oder nicht, werde ich auch nicht gefragt...

**Comment by gharlan** [comment]
Habt ihr die Beta bei euch bewusst aktiviert?
Bei mir gab es dafür einen Link, habe es nun auch mal aktiviert und kann das Problem nun nachvollziehen.

Blöd, dass die Beta über eine eigene Domain läuft. Sobald die finalisiert wird, wird sich die Domain ja vermutlich wieder ändern.

Leider finde ich auch keinen Link, um die Beta für meinen Account wieder zu deaktivieren.

**Comment by gharlan** [comment]
Ich habe doch einen Link gefunden:
Rechts unten auf der neuen Website sollte so ein großes Fragezeichen erscheinen. Klicke ich darauf, erscheint unten ein Link "gehe zurück zur alten Shoop.de Webseite".
Danach funktioniert der Abruf in MoneyMoney wieder.

**Comment by ruaq** [comment]
Vielen Dank @gharlan - Mit Deinem Tipp hat es funktioniert!

**Comment by zenminimalist** [comment]
Also ich bekomme folgende Meldung: 
 
```
Login successful.
  Shoop.lua: expected string for 'account.accountNumber'
          Konnte die Kontenliste nicht abfragen.
```
Beta o.ä. habe ich nicht aktiviert. Dieses Problem trat erst vor ein paar Tagen bei mir auf.

**Comment by gharlan** [comment]
Mittlerweile wurde bei allen die Website umgestellt, und es gibt keine Beta mehr.
Ich muss nun die Extension anpassen, versuche das zeitnah zu erledigen.
Derweil würde ich in die Einstellung des Kontos gehen, und da bei Aktualisierung "nur manuell" auswählen, bis es hier Neues von mir gibt.

**Comment by gharlan** [comment]
Ich habe die Extension nun aktualisiert (1.02), und an den Moneymoney-Entwickler gesendet. Müssen nun nur noch warten, bis sie auch hier erscheint: https://moneymoney-app.com/extensions/

**Comment by gharlan** [comment]
Die neue Version ist nun hier verfügbar: https://moneymoney-app.com/extensions/

**Comment by zenminimalist** [comment]
Danke, allerdings funktioniert bei mir die aktualisierte Version nicht. Ich habe dann das Konto gelöscht und versucht neu hinzuzufügen, ohne Erfolg.

`15:36:49  Received: {"result":"success","message":
          Shoop.lua: expected number for 'transaction.amount', transaction data `2018-11-26 12:00:00 +0000/eBay//
          Sending: DELETE https://api.shoop.de/api/auth/
          Received: {"result":"success","message":[true]}
          Logout successful.
          Konnte die Umsätze nicht abfragen.
          Received 0 transactions.
          Konnte die Kontenliste nicht abfragen.`

Was könnte das Problem sein?

**Comment by gharlan** [comment]
Am 26.11. hast du scheinbar eine eBay-Transaktion. Ist damit irgendwas besonderes? Hat die Transaktion einen Cashback-Betrag (auf der shoop-Website)?

**Comment by zenminimalist** [comment]
Nicht das ich sehen kann. Diese ist erfasst und hat auch einen festen Betrag. Und am 26.11 gibt es zudem eine Erinnung als Transaktion. Diese Feature ist glaube ich neu und nicht in deinem Code reflektiert sein. Diese Transaktionen sollen übersprungen werden.

**Comment by gharlan** [comment]
In der Tat lag es an der Erinnerung.
Habe eine neue Version eingereicht.

**Comment by zenminimalist** [comment]
Top, probiere ich gleich aus, sobald die 1.03 auf der Webseite ist und gebe Bescheid! Danke fürs schnelle ändern!

**Comment by zenminimalist** [comment]
Jetzt funktioniert das ganze! Nochmal Danke!

**Comment by christophbach** [comment]
Hallo Gregor,
entschuldige die späte Rückmeldung. Die Extension läuft einwandfrei. Danke!
