### ISSUE TITLE
140 bad argument

### ISSUE THREAD

**Issue by zenminimalist** [gharlan/moneymoney-shoop#3]
Ich habe gerade beim Shoop Plugin diesen Fehler bekommen, kann ihn aber nicht interpretieren.
![IMG_0202](https://user-images.githubusercontent.com/7798503/92956232-d116df00-f466-11ea-8d43-721a86ccb800.png)
Irgendwelche Ideen? Oder ist das nur ein temporäres Problem?

**Comment by zenminimalist** [comment]
@gharlan Ich werde daraus nicht schlau. Ich habe mal im Log nachgeschaut:

`1> Login successful.
          1> Lade Kontostand und Umsätze für Shoop ...
          1> Getting transactions since 22.06.2020...
          1> Sending: GET https://api.shoop.de/api/user/
          1> Received: {"result":"success","message":{"transactions":
          1> Sending: GET https://api.shoop.de/api/user/payouts/?from=2014-01-01T00:00:00.000Z
          1> HTTPS response: HTTP/1.1 404 Not Found
          1> Received: {"result":"error","message":["Es ist ein Fehler aufgetaucht. Wir wurden dar\u00fcber informiert."]}
          1> Shoop.lua:140: bad argument #1 to 'ipairs' (table expected, got nil)`

Der Code scheint eine Tabelle zu erwarten bekommt sie aber nicht. Warum weiß ich leider nicht, da ich kein Programmierer bin und somit keine Superpowers habe. : (

**Comment by gharlan** [comment]
Ich kann auf jeden Fall bestätigen, dass ich hier das Problem auch habe. Ich bin aber noch nicht dazu gekommen, meine Superpower anzuwerfen und es mir genauer anzuschauen.

**Comment by zenminimalist** [comment]
Ok, dann liegt es nicht nur an mir.

**Comment by rriixx** [comment]
gleiches problem bei mir

**Comment by christophbach** [comment]
Ist das jeweils euer aktueller Kontostand oder hattet ihr vorher auszahlen lassen?

**Comment by zenminimalist** [comment]
@christophbach Auszahlen habe ich mir schon lange nichts. Und der Kontostand stimmt zumindest überein. Allerdings weiß ich nicht ob das Zufall ist, bzw. wenn noch eine Transaktion morgen z.B. verfügbar ist, ob sich der Kontostand aktualisieren würde.

**Comment by christophbach** [comment]
@zenminimalist Ok, ich hatte kurz bevor der Fehler auftrat, ausgezahlt und vermutet, dass der mit einem Wert von 0,00 nicht klarkommt. Zwar eher unwahrscheinlich, aber somit klar ausgeschlossen. :)

**Comment by gharlan** [comment]
Die Struktur der internen API der Shoop-Website hatte sich geändert. 
Ich habe die Extension nun dafür angepasst, und sie an den MoneyMoney-Entwickler gesendet.
Ihr müsst nun also nur noch warten, bis die Version 1.04 hier zur Verfügung gestellt wurde: https://moneymoney-app.com/extensions/

**Comment by zenminimalist** [comment]
@gharlan We bow to you, Obi-Wan! May the programming powers be ever with you!

**Comment by gharlan** [comment]
Das Update liegt nun bereit: https://moneymoney-app.com/extensions/

**Comment by zenminimalist** [comment]
Ich bekomme immer noch einen Fehler. 

`Shoop.lua:118: attempt to index local 'row' (a nil value)`

MM habe ich vorher neugestartet und auch sichergestellt, dass es die 1.04 Version ist. Liegt das vielleicht nur an mir?

**Comment by gharlan** [comment]
Scheinbar hast du irgendwas in deinen Transaktionen, was ich bei mir nicht habe und daher nicht kenne, und somit scheinbar nicht korrekt behandle.
https://www.shoop.de/aktivitaeten/bestellungen
Fällt dir da bei dir irgendwas selbst auf, was aus der Reihe tanzt?
(Ich habe da bei mir Transaktionen mit Status "erfasst", "verfügbar", "abgelehnt" oder "ausgezahlt".)

**Comment by zenminimalist** [comment]
So sieht es bei mir aus:

![CleanShot 2020-09-25 at 17 36 38@2x](https://user-images.githubusercontent.com/7798503/94286936-f40cbd00-ff55-11ea-9561-ae6055f8c05d.png)

Also nichts ausgewöhliches.

**Comment by MelleD** [comment]
Ich bekomme die gleiche Meldung
Shoop.lua:118: attempt to index local 'row' (a nil value)

Könnte es daran liegen, dass ich einen Eintrag habe wo der Warenkorb leer ist.

<img width="1115" alt="Bildschirmfoto 2020-09-28 um 22 10 23" src="https://user-images.githubusercontent.com/6340898/94481140-94254900-01d7-11eb-8a1d-f32feefa1f7f.png">

**Comment by zenminimalist** [comment]
@MelleD Ich glaube das steckt noch was anders dahinter, wenn es bei mir auch nicht funktioniert.

**Comment by MelleD** [comment]
Aber das ist die einzige Row, die keinen Wert hat. Seh gerade ist auf dem Bild schlecht weil die Überschriften fehlen. Nachdem 5,00€ kommt normal der Warenkorb Wert.

@zenminimalist kannst deine Liste ja mal durschauen, ob du auch so einen älteren Eintrag hast. Du hast ja bestimmt noch mehr Seiten.

**Comment by zenminimalist** [comment]
@MelleD Also einen identischen Eintrag mit Warenkorbwert 0 EUR habe ich nicht. Von daher gehe ich davon aus, dass das Problem woanders liegt.

**Comment by MelleD** [comment]
@zenminimalist Warenkorb 0,00 Euro habe ich auch aber ich habe auch einen Warenkorb nicht da, da steht einfach nichts.

**Comment by rriixx** [comment]
@gharlan danke für den fix! bei mir funktioniert es

**Comment by markwiesemann** [comment]
Bei mir tritt der Fehler auch auf. Ich konnte das Problem auf eine Bonuszahlung von Shoop eingrenzen. Hier der leicht anonymisierte JSON-Schnipsel aus dem MoneyMoney-Protokoll:

    {"type":"bonus","bonus":{"logoDetails":{"fav":{"normal":"https:\/\/files.shoop.de\/u\/logos\/favico\/1817.png","retina":"https:\/\/files.shoop.de\/u\/logos\/favico\/1817.png"},"small":{"normal":"https:\/\/files.shoop.de\/u\/merchant_logo\/bonuszahlungen_an_user_or.svg","retina":"https:\/\/files.shoop.de\/u\/merchant_logo\/bonuszahlungen_an_user_or.svg"},"medium":{"normal":"https:\/\/files.shoop.de\/u\/merchant_logo\/bonuszahlungen_an_user_or.svg","retina":"https:\/\/files.shoop.de\/u\/merchant_logo\/bonuszahlungen_an_user_or.svg"},"big":{"normal":"https:\/\/files.shoop.de\/u\/merchant_logo\/bonuszahlungen_an_user_or.svg","retina":"https:\/\/files.shoop.de\/u\/merchant_logo\/bonuszahlungen_an_user_or.svg"}},"transactionId":2345678,"merchantName":"Bonus","trackedDate":"2019-09-20T22:54:33+02:00","status":{"type":"paid","text":"ausgezahlt"},"cashback":5,"notes":"","isEnquiryAllowed":false,"ticketId":null,"ticketIds":[],"enquiryDate":null,"enquiryDates":[],"special":{"type":null,"text":null},"validatingTransaction":{"merchantName":"Groupon","status":{"type":"paid","text":"ausgezahlt"},"transactionId":1234567,"cashback":0.93},"progress":[{"heading":"tracked","label":"Erfasst","date":"2019-09-20T22:54:33+02:00","text":null,"premiumText":null,"active":false},{"heading":"available","label":"Verf\u00fcgbar","date":"2019-11-19T17:07:46+01:00","text":null,"premiumText":null,"active":false},{"heading":"paid","label":"Ausgezahlt","date":"2019-11-28T19:17:41+01:00","text":"Der Bonus wurde bereits per Voucher ausgezahlt.","premiumText":null,"active":true}],"payments":[{"id":2501279,"method":"voucher","methodLabel":"Wertgutschein","premiumPeriod":null,"date":"2019-11-28T19:17:41+01:00","amount":5}]}}

**Comment by zenminimalist** [comment]
@markwiesemann Bei mir gibt es auch eine Bonuszahlung von Shoop. Das scheint tatsächlich das Problem zu sein. Bei dir auch @MelleD?

**Comment by gharlan** [comment]
Danke für die Infos, insbesondere das JSON-Schnipsel ist sehr hilfreich.
Darauf basierend habe ich nun versucht, die Bonus-Zahlungen auch zu unterstützen.

Eine Testversion gibt es hier: https://raw.githubusercontent.com/gharlan/moneymoney-shoop/bonus/Shoop.lua
Es wäre super, wenn das einer testen könnte:
- MoneyMoney beta laden
- In MoneyMoney Einstellungen bei Erweiterungen die Checkbox "Digitale Signatur von Extensions überprüfen" temporär deaktivieren
- Im Hilfe-Menü auf "Zeige Datenbank im Finder" klicken. Parallel zu dem Ordner liegt der Ordner "Extensions"
- Darin die Shoop.lua austauschen mit der oben verlinkten Datei

**Comment by markwiesemann** [comment]
Danke für die schnelle Reaktion. Die neue Testversion funktioniert bei mir. Die Bonuszahlung wird korrekt angezeigt.

**Comment by MelleD** [comment]
@zenminimalist  siehe Bild von mir da siehst genau die Bonuszahlung ;)

**Comment by gharlan** [comment]
Es gibt nun die neue Version als signierte Extension auf der MoneyMoney-Website.

**Comment by zenminimalist** [comment]
@gharlan Jetzt funktioniert es bei mir einwandfrei!
