### ISSUE TITLE
Fehler HTTP 404 

### ISSUE THREAD

**Issue by markwiesemann** [gharlan/moneymoney-shoop#7]
Hallo,

seit kurzem scheitert der Abruf der Shoop-Einträge in MoneyMoney bei mir. Hier ein Auszug aus dem Log:

+++
20:04:20  Starting login data assistant.
20:04:27  Lade Kontenliste ...
          Web Banking Engine: Using user-supplied extension Shoop.lua version 1.06.
          Protocol version: Web Scraping
20:04:28  Server address: https://www.shoop.de
          Sending: POST https://api.shoop.de/api/auth/
          HTTPS response: HTTP/1.1 404 Not Found
          Received: {"result":"error","message":["Es ist ein Fehler aufgetaucht. Wir wurden dar\u00fcber informiert."]}
          Ihre Zugangsdaten (Benutzername, Passwort) wurden vom Server Ihrer Bank als ungültig abgewiesen. Bitte überprüfen Sie noch einmal Ihre Zugangsdaten.
20:04:32  Canceled login data assistant.
+++

Ich habe mir den Login auf shoop.de angesehen. Dort wird die Adresse aus dem POST-Request immer noch benutzt. Genauere Analysen habe ich ansonsten noch nicht vorgenommen.

**Comment by Lars147** [comment]
Gleiches Problem bei mir

**Comment by markwiesemann** [comment]
Danke, mit dem neuen Code funktioniert es wieder. Kleine Änderung, große Wirkung.
