### ISSUE TITLE
extension not recognised by moneyMoney anymore

### ISSUE THREAD

**Issue by MagicChocoRolls** [gharlan/moneymoney-shoop#8]
Hey there,

I updated to the latest version of the extension as it was not working anymore. Now the extension is not even recognised by moneyMoney anymore.

**Comment by MagicChocoRolls** [comment]
additional info: 
<img width="465" alt="image" src="https://github.com/gharlan/moneymoney-shoop/assets/23453415/d119e9d9-d8b4-4752-a114-3d407c734a96">

**Comment by gharlan** [comment]
You have to use the signed version from https://moneymoney-app.com/extensions/. It is the latest version.

Unsigned versions from github can be used in MoneyMoney Beta, see https://moneymoney-app.com/api/webbanking/:
> Hinweis: Für die Entwicklung eigener Extensions lässt sich die Überprüfung der digitalen Signatur in den Einstellungen von MoneyMoney ausschalten. Dazu wird eine [Beta-Version](https://moneymoney-app.com/beta) von MoneyMoney benötigt. Die Option lässt sich mit der Menüfunktion »MoneyMoney« → »Einstellungen« → »Erweiterungen« → »Digitale Signatur von Extensions überprüfen« erreichen.
